// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAssets():Promise<Array<main.Video>>;

export function GetPresignedUrl(arg1:main.File):Promise<string>;
